Create abnormallyPrematureBiologicalProcessInLocation,yaml
obophenotype/upheno pull request #743
Opened 2021-06-02 19:44 UTC by pfey03

seems to look good

2021-06-02 20:32 UTC, matentzn requested changes

2021-06-02 20:32 UTC, matentzn commented on src/patterns/dosdp-dev/abnormallyPrematureBiologicalProcessInLocation,yaml
> +  text: "premature %s"
misisng location

2021-06-02 20:32 UTC, matentzn commented on src/patterns/dosdp-dev/abnormallyPrematureBiologicalProcessInLocation,yaml
> +pattern_name: abnormallyPrematureBiologicalProcessInLocation
the filename has a comma, not a period :)

![Uploading image.png…]()

2021-06-02 20:32 UTC, matentzn commented on src/patterns/dosdp-dev/abnormallyPrematureBiologicalProcessInLocation,yaml
> +pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyPrematureBiologicalProcess.yaml
iri has wrong name

2021-06-11 22:25 UTC, pfey03 reviewed
approve of all changes, using patterns already

2021-06-11 22:28 UTC, pfey03 commented
@matentzn trying to move this forward is it ok now? Thanks!

2021-06-13 10:22 UTC, matentzn requested changes

2021-06-13 10:22 UTC, matentzn commented on src/patterns/dosdp-dev/abnormallyPrematureBiologicalProcessInLocation,yaml
> +pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyPrematureBiologicalProcess.yaml
Still wrong: Missing InLocation!

2021-06-13 10:22 UTC, matentzn commented on src/patterns/dosdp-dev/abnormallyPrematureBiologicalProcessInLocation,yaml
> +pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyPrematureBiologicalProcess.yaml
Thats would be correct!

2021-06-13 10:22 UTC, matentzn commented on src/patterns/dosdp-dev/abnormallyPrematureBiologicalProcessInLocation.yaml
> +  text: "premature %s"
Still missing location (the text needs to contain %s twice, once or the biological process, once for the location)

2021-06-23 08:45 UTC, matentzn commented
@pfey03 This still requires some changes from your end to be merged! Thanks :)

2021-06-23 13:42 UTC, pfey03 commented on src/patterns/dosdp-dev/abnormallyPrematureBiologicalProcessInLocation.yaml
> +  text: "premature %s"
I clicked everywhere but don't know how to edit the file in a branch. I edited the file but it didn't take it and it says I ned to do in branch but how?

2021-06-23 13:51 UTC, matentzn commented
Click here: https://github.com/obophenotype/upheno/pull/743/files

Then:

![image](https://user-images.githubusercontent.com/7070631/123108535-69001b00-d432-11eb-8e8e-079e5e22965e.png)

2022-01-19 12:51 UTC, matentzn approved these changes

2022-01-19 13:12 UTC, merged