abnormallyDelayedBiologicalProcessInLocation.yaml
obophenotype/upheno pull request #751
Opened 2021-06-11 22:53 UTC by pfey03

hope I got everything this time

2021-06-23 08:43 UTC, matentzn approved these changes

2021-06-28 08:19 UTC, Clare72 requested changes

2021-06-28 08:19 UTC, Clare72 commented on src/patterns/abnormallyDelayedBiologicalProcessInLocation.yaml
> +  text: "delayed %s"
should be "delayed %s in %s" - same for definition.

2022-01-19 12:53 UTC, matentzn approved these changes

2022-01-19 13:06 UTC, Clare72 approved these changes

2022-01-19 13:21 UTC, merged