Add new ivory anatomical entity pattern templates
obophenotype/upheno pull request #824
Opened 2022-04-28 15:07 UTC by rays22

If applied, this commit will fix #823.

2022-05-19 16:08 UTC, sbello commented
fine with me: orcid.org/0000-0003-4606-0597

2022-05-19 16:08 UTC, anna-anagnostop commented
Ok with me Anna Anagnostopoulos https://orcid.org/0000-0002-6490-7723

2022-05-19 16:08 UTC, matentzn commented
ok by me https://orcid.org/0000-0002-7356-1779

2022-05-19 16:10 UTC, LCCarmody commented
Okay. https://orcid.org/
0000-0001-7941-2961

2022-05-19 16:11 UTC, rays22 commented on src/patterns/dosdp-dev/abnormallyIvoryAnatomicalEntity.yaml
> +description: 'Please, note that the term "ivory" in the context of this phenotype pattern refers to the increased density of an anatomical entity (e.g. epiphysis) observable by radiography (X-rays).'
Strip off 'Please, note...'

2022-05-19 16:12 UTC, rays22 commented on src/patterns/dosdp-dev/abnormallyIvoryAnatomicalEntityInLocation.yaml
> +description: 'Please, note that the term "ivory" in the context of this phenotype pattern refers to the increased density of an anatomical entity (e.g. epiphysis) observable by radiography (X-rays).
Strip off 'Please, note...'

2022-05-19 16:18 UTC, matentzn requested changes

2022-05-19 16:18 UTC, matentzn commented on src/patterns/dosdp-dev/abnormallyIvoryAnatomicalEntity.yaml
> +            'has_modifier' some 'abnormal')"
"'has_part' some (
            'ivory' and
            ('characteristic_of' some %s) and
            ('has_modifier' some 'abnormal'))"

Better use brackets () to ensure  correct unin

2022-05-19 16:18 UTC, matentzn commented on src/patterns/dosdp-dev/abnormallyIvoryAnatomicalEntity.yaml
> +description: 'Please, note that the term "ivory" in the context of this phenotype pattern refers to the increased density of an anatomical entity (e.g. epiphysis) observable by radiography (X-rays).'
remove please note and consider standard pattern description text.

2022-05-19 16:18 UTC, matentzn commented on src/patterns/dosdp-dev/abnormallyIvoryAnatomicalEntity.yaml
> +pattern_name: abnormallyIvoryAnatomicalEntity
drop abnormal from pattern name

2022-05-19 16:18 UTC, matentzn commented on src/patterns/dosdp-dev/abnormallyIvoryAnatomicalEntity.yaml
> +pattern_iri: http://purl.obolibrary.org/obo/upheno/patterns-dev/abnormallyIvoryAnatomicalEntity.yaml
drop abnormally from the pattern name, just ivoryAnatomicalEntity

2022-05-19 16:18 UTC, matentzn commented on src/patterns/dosdp-dev/abnormallyIvoryAnatomicalEntity.yaml
> +  text: "An abnormal increase in the radiographic density of %s."
Make more close to pato def.

2022-05-19 16:18 UTC, matentzn commented on src/patterns/dosdp-dev/abnormallyIvoryAnatomicalEntity.yaml
> +...
what are the three dots there?

2022-05-19 16:18 UTC, matentzn commented on src/patterns/dosdp-dev/abnormallyIvoryAnatomicalEntityInLocation.yaml
> +pattern_name: abnormallyIvoryAnatomicalEntityInLocation
see above

2022-05-20 20:02 UTC, rays22 commented on src/patterns/dosdp-dev/abnormallyIvoryAnatomicalEntity.yaml
> +...
Three dots ( “...”) indicate the end of a [yaml 1.2.2 document without starting a new one.](https://yaml.org/spec/1.2.2/#22-structures)
For consistency with the other yaml files here, I will remove them.

2022-05-20 20:22 UTC, merged