Add wrinkled anatomical entity DOS-DP pattern draft
obophenotype/upheno pull request #860
Opened 2022-07-22 17:51 UTC by rays22

for community review.

If applied, this commit will fix #858.

2022-07-24 16:25 UTC, matentzn commented on src/patterns/dosdp-dev/wrinkledAnatomicalEntity.yaml
> +...
I am really worried about these three dots at the end of every pattern.. Why are these there?

2022-07-24 16:25 UTC, matentzn commented on src/patterns/dosdp-dev/wrinkledAnatomicalEntity.yaml
> +#  examples:
why are the examples commented out?

2022-07-28 16:37 UTC, sbello requested changes

2022-07-28 16:37 UTC, sbello commented on src/patterns/dosdp-dev/wrinkledAnatomicalEntity.yaml
> +#  examples:
add example 
wrinkled skin MP:0001211
ZP:0015987 http://purl.obolibrary.org/obo/ZP_0015987

examples were commented out until review

2022-07-28 16:37 UTC, sbello commented on src/patterns/dosdp-dev/wrinkledAnatomicalEntity.yaml
> +...
I do not know, will ask Ray

2022-08-17 14:25 UTC, rays22 commented on src/patterns/dosdp-dev/wrinkledAnatomicalEntity.yaml
> +...
> I am really worried about these three dots at the end of every pattern.. Why are these there?

They are [yaml 1.2.0 end of document markers](https://yaml.org/spec/1.2.0/#id2599514).
I get a warning from [yamlint](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.document_end) if I leave them out.

2022-08-17 14:33 UTC, rays22 commented on src/patterns/dosdp-dev/wrinkledAnatomicalEntity.yaml
> +#  examples:
> why are the examples commented out?

Examples are not yet implemented in DOS-DP tools and thus the validation fails unless I comment them out. I will come back and fix them after the examples section gets implemented in DOS-DP tools.

2022-08-17 15:17 UTC, merged